use_frameworks!

platform :ios, '13.0'

target 'ScaleCodecSwift_Example' do
  pod 'ScaleCodecSwift', :path => '../'
  pod 'CommonSwift', :git => 'https://github.com/sublabdev/common-swift.git', :commit => '5bdbe0884ebbdaa8bec9b2f73133764c489d180f'

  target 'ScaleCodecSwift_Tests' do
    inherit! :search_paths

    
  end
end
