use_frameworks!

platform :ios, '13.0'

target 'ScaleCodecSwift_Example' do
  pod 'ScaleCodecSwift', :path => '../'
  pod 'CommonSwift', :git => 'https://github.com/sublabdev/common-swift.git', :commit => '6c4d9b646328e9aa1769111d68dfb94f6055c9f1'

  target 'ScaleCodecSwift_Tests' do
    inherit! :search_paths

    
  end
end
